services:
  localstack:
    image: localstack/localstack:3.4.0
    ports:
      - "4566:4566"  # LocalStack main port
      - "4576:4576"  # SQS port
    environment:
      - SERVICES=sqs
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"